export type Certification = "GIA" | "IGI" | "None";

export interface Diamond {
  id: number;
  stockId: string;
  type: "natural" | "lab" | "loose";
  shape: string;
  carat: number;
  color: string;
  clarity: string;
  cut: string;
  polish: string;
  symmetry: string;
  fluorescence: string;
  measurements: string;
  image: string;
  certification: Certification;
  imageUrl?: string;
  images?: string[];
  videoUrl?: string;
  giaReportUrl?: string;
  giaReportPdfUrl?: string;
  certificateNumber?: string;
  /* ── Extended trade fields ── */
  loc?: string;
  lab?: string;
  rap?: number;
  rapVal?: number;
  listedPrCt?: number;
  listedDisc?: number;
  listedAmt?: number;
  tableP?: number;
  shade?: string;
  depth?: number;
  certNo?: string;
  ratio?: number;
  ca?: number;
  ch?: number;
  girdlePct?: number;
  pa?: number;
  ph?: number;
  lh?: number;
  sl?: number;
  culet?: string;
  girdleDesc?: string;
  tb?: string;
  sb?: string;
  tInc?: string;
  sInc?: string;
  tableOpen?: string;
  co?: string;
  po?: string;
  milky?: string;
  ec?: string;
  rptCom?: string;
  keyToSymbols?: string;
  ins?: string;
  luster?: string;
  origin?: string;
  tracrId?: string;
  ha?: string;
}
