import { defineType, defineField } from "sanity";

export default defineType({
  name: "investmentPage",
  title: "Investment Page",
  type: "document",
  fields: [
    defineField({ name: "seo", title: "SEO", type: "seoObject" }),
    defineField({
      name: "heroTagline",
      title: "Hero Tagline (overline)",
      type: "string",
      initialValue: "Investment Grade",
    }),
    defineField({
      name: "heroHeading",
      title: "Hero Heading",
      type: "string",
      initialValue: "Diamonds as a Portable, Stateless Asset.",
    }),
    defineField({
      name: "heroSubtext",
      title: "Hero Subtext",
      type: "text",
      rows: 3,
      initialValue: "Natural FL diamonds represent the apex of the GIA grading scale. We work with serious buyers — private individuals and institutional — seeking certifiable hard assets outside the share market.",
    }),
    defineField({
      name: "heroCta",
      title: "Hero CTA Label",
      type: "string",
      initialValue: "Book a Consultation",
    }),
    defineField({
      name: "heroSecondaryCta",
      title: "Hero Secondary CTA Label",
      type: "string",
      initialValue: "Browse IF→FL Inventory",
    }),
    defineField({
      name: "heroImage",
      title: "Hero Image",
      type: "image",
      options: { hotspot: true },
    }),
    defineField({
      name: "assetClassTagline",
      title: "Asset Class Section Tagline",
      type: "string",
      initialValue: "The Case for Diamonds",
    }),
    defineField({
      name: "assetClassHeading",
      title: "Asset Class Section Heading",
      type: "string",
      initialValue: "Why natural FL diamonds hold value.",
    }),
    defineField({
      name: "assetClassPoints",
      title: "Asset Class Points",
      type: "array",
      of: [{
        type: "object",
        fields: [
          { name: "title", type: "string", title: "Title" },
          { name: "body", type: "text", title: "Body", rows: 3 },
          { name: "tag", type: "string", title: "Tag/Badge" },
        ],
        preview: { select: { title: "title" } },
      }],
      initialValue: [
        { title: "Wealth Preservation", body: "Natural FL diamonds in D–F colour have held and appreciated in AUD terms over 10-year periods. No counterparty risk. No custodian required.", tag: "Hard asset" },
        { title: "Rarity Premium", body: "FL and IF in D–F colour represent less than 1% of all GIA-graded stones globally. Supply cannot be manufactured on demand.", tag: "Top 1%" },
        { title: "Value Transparency", body: "Every stone has a GIA certificate with a unique number, publicly verifiable. The IF→FL uplift creates a new, independent certificate — the value created is documented and auditable.", tag: "GIA verifiable" },
      ],
    }),
    defineField({
      name: "rarityTagline",
      title: "Rarity Section Tagline",
      type: "string",
      initialValue: "The GIA Scale",
    }),
    defineField({
      name: "rarityHeading",
      title: "Rarity Section Heading",
      type: "string",
      initialValue: "The Apex of Rarity: GIA Flawless.",
    }),
    defineField({
      name: "rarityBody",
      title: "Rarity Section Body",
      type: "text",
      rows: 4,
      initialValue: "The GIA Flawless grade means no internal or external characteristics are visible under 10× magnification to a skilled grader. It is the pinnacle of clarity — and the destination of our IF→FL conversion work.",
    }),
    defineField({
      name: "conversionTagline",
      title: "Conversion Process Tagline",
      type: "string",
      initialValue: "The Uplift Process",
    }),
    defineField({
      name: "conversionHeading",
      title: "Conversion Process Heading",
      type: "string",
      initialValue: "Six Steps from IF to Flawless.",
    }),
    defineField({
      name: "conversionSteps",
      title: "Conversion Process Steps",
      type: "array",
      of: [{
        type: "object",
        fields: [
          { name: "step", type: "string", title: "Step Number (e.g. 01)" },
          { name: "label", type: "string", title: "Step Label" },
          { name: "body", type: "text", title: "Step Description", rows: 3 },
        ],
        preview: { select: { title: "label", subtitle: "step" } },
      }],
    }),
    defineField({
      name: "profitSplitHeading",
      title: "50/50 Profit Split Heading",
      type: "string",
      initialValue: "We only earn when you earn — 50/50 profit split.",
    }),
    defineField({
      name: "profitSplitBody",
      title: "50/50 Profit Split Body",
      type: "text",
      rows: 3,
      initialValue: "No upfront cost. No conversion fee. We calculate the IF value, the projected FL value, document it in writing, then share the profit we create together.",
    }),
    defineField({
      name: "ctaHeading",
      title: "Consultation CTA Heading",
      type: "string",
      initialValue: "Ready to explore your stone's potential?",
    }),
    defineField({
      name: "ctaBody",
      title: "Consultation CTA Body",
      type: "text",
      rows: 2,
      initialValue: "Whether you hold an IF stone or are looking to acquire an FL-grade asset, start with a conversation. No obligation, no salesmanship.",
    }),
    defineField({
      name: "pillars",
      title: "Pillars (Why FL diamonds hold value)",
      type: "array",
      of: [{
        type: "object",
        fields: [
          { name: "title", title: "Title", type: "string" },
          { name: "body", title: "Body", type: "text", rows: 3 },
        ],
        preview: { select: { title: "title" } },
      }],
    }),
    defineField({ name: "processTagline", title: "Process Section Tagline", type: "string" }),
    defineField({ name: "processHeading", title: "Process Section Heading", type: "string" }),
    defineField({
      name: "processSteps",
      title: "Process Steps",
      type: "array",
      of: [{
        type: "object",
        fields: [
          { name: "n", title: "Step Number (e.g. 01, ?, FL)", type: "string" },
          { name: "tag", title: "Tag", type: "string" },
          { name: "title", title: "Title", type: "string" },
          { name: "body", title: "Body", type: "text", rows: 3 },
        ],
        preview: { select: { title: "title", subtitle: "n" } },
      }],
    }),
    defineField({ name: "casestudiesTagline", title: "Case Studies Tagline", type: "string" }),
    defineField({ name: "casestudiesHeading", title: "Case Studies Heading", type: "string" }),
    defineField({ name: "casestudiesSubtext", title: "Case Studies Subtext", type: "text", rows: 3 }),
    defineField({
      name: "galleryImages",
      title: "Process / Gallery Images (legacy)",
      description: "Legacy image-only list for the horizontal process panels. Prefer using 'IF→FL Scroll Panels' below, which lets you edit the text AND the image for each panel.",
      type: "array",
      of: [{ type: "image", options: { hotspot: true } }],
    }),
    defineField({
      name: "conversionPanels",
      title: "IF→FL Scroll Panels",
      description: "The horizontal scroll journey on the Investment page. Each entry is one full-screen panel. Edit the tag, title, body, image and image alt-text. Use a line break in the Title to control where it wraps.",
      type: "array",
      of: [{
        type: "object",
        fields: [
          { name: "type", title: "Panel Type", type: "string",
            options: { list: [
              { title: "Intro", value: "intro" },
              { title: "Step", value: "step" },
              { title: "Decision", value: "decision" },
              { title: "End / Result", value: "end" },
            ], layout: "radio" },
            initialValue: "step" },
          { name: "step", title: "Badge Label", type: "string",
            description: 'Short label shown in the corner badge, e.g. "01", "?", "FL". Leave empty for the intro panel.' },
          { name: "tag", title: "Eyebrow / Tag", type: "string",
            description: 'Small uppercase label, e.g. "Free · 24 h response".' },
          { name: "title", title: "Title", type: "text", rows: 2,
            description: "Use a line break to control wrapping." },
          { name: "body", title: "Body", type: "text", rows: 3 },
          { name: "image", title: "Image", type: "image", options: { hotspot: true } },
          { name: "imgAlt", title: "Image Alt Text", type: "string" },
        ],
        preview: { select: { title: "title", subtitle: "tag", media: "image" } },
      }],
      initialValue: [
        { type: "intro", step: "", tag: "The Exact Process", title: "Six Steps from IF\nto Flawless.", body: "A documented, repeatable path from GIA IF certificate to GIA FL certificate. Every stage is defined. Every outcome is verifiable.", imgAlt: "FL diamond — overhead" },
        { type: "step", step: "01", tag: "Free · 24 h response", title: "Submit Your\nGIA Certificate", body: "Send us the certificate number. We read the GIA Comments field — specific language such as 'extra facet' or 'surface graining' is the key indicator of conversion candidacy.", imgAlt: "GIA FL Certificate" },
        { type: "step", step: "02", tag: "Technical GIA reading", title: "We Read Between\nthe Grades", body: "Our team decodes the GIA Comments section. An IF grade often contains surface characteristics invisible to the naked eye — and removable without touching carat weight.", imgAlt: "Diamond analysis" },
        { type: "decision", step: "?", tag: "~15–20% of IF stones qualify", title: "Does Your Stone\nQualify?", body: "The surface characteristic must be removable without crossing the carat threshold. Roughly 1 in 5 IF stones pass this filter. You receive a clear yes or no — at no cost.", imgAlt: "Diamond qualification" },
        { type: "step", step: "03", tag: "Written · No obligation", title: "A Clear,\nWritten Assessment", body: "If the stone qualifies, we deliver a written feasibility report — projected FL outcome, timeline, and cost structure. No commitment required at this stage.", imgAlt: "Written assessment" },
        { type: "step", step: "04", tag: "47 years · Babu Vekariya", title: "The Craft of\nPrecision", body: "Babu Vekariya executes the precision micro-regrind. Under 0.01mm removed from the affected facet. Hours per stone. No automation, no margin for error.", imgAlt: "Precision regrind" },
        { type: "end", step: "FL", tag: "Value uplift: 15–35%", title: "Your Stone.\nReborn Flawless.", body: "The stone is independently resubmitted to GIA. A new Flawless certificate is issued — same carat bracket, verifiable, permanent, globally recognised.", imgAlt: "FL diamond — result" },
      ],
    }),
  ],
  preview: { prepare: () => ({ title: "Investment Page" }) },
});